<# 
capture_api_pins.ps1 - generate SPKI SHA-256 pins for ZeusWatch's keyed endpoints.

Writes a formatted Kotlin snippet to stdout that can be pasted into
ApiCertificatePins.hostPins. Captures the full chain (leaf + intermediates)
so rotation does not brick the app when only one certificate changes.

Requires: openssl on PATH.

Usage:
  .\tools\capture_api_pins.ps1
  .\tools\capture_api_pins.ps1 api.openweathermap.org:443 api.pirateweather.net:443
#>

[CmdletBinding()]
param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]] $Endpoints = @(
        "api.openweathermap.org:443",
        "api.pirateweather.net:443"
    )
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-OpenSsl {
    $cmd = Get-Command openssl -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Source
    }

    $candidates = @(
        "$env:ProgramFiles\Git\usr\bin\openssl.exe",
        "$env:ProgramFiles\Git\mingw64\bin\openssl.exe"
    )
    if (${env:ProgramFiles(x86)}) {
        $candidates += "${env:ProgramFiles(x86)}\Git\usr\bin\openssl.exe"
        $candidates += "${env:ProgramFiles(x86)}\Git\mingw64\bin\openssl.exe"
    }

    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) {
            return $candidate
        }
    }

    throw "openssl not found on PATH or in the default Git for Windows locations"
}

$OpenSsl = Resolve-OpenSsl

function Invoke-OpenSslText {
    param(
        [Parameter(Mandatory = $true)][string[]] $Arguments,
        [switch] $PipeEmptyInput
    )

    $previousPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        if ($PipeEmptyInput) {
            $output = "" | & $OpenSsl @Arguments 2>&1
        } else {
            $output = & $OpenSsl @Arguments 2>&1
        }
        $exitCode = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $previousPreference
    }

    if ($exitCode -ne 0) {
        throw "openssl failed with exit code $exitCode for arguments: $($Arguments -join ' ')"
    }

    @($output | ForEach-Object { $_.ToString() })
}

function Split-Endpoint {
    param([Parameter(Mandatory = $true)][string] $Endpoint)

    $parts = $Endpoint.Split(":", 2)
    if ($parts.Count -eq 1) {
        return [pscustomobject]@{ Host = $Endpoint; Port = "443" }
    }
    return [pscustomobject]@{ Host = $parts[0]; Port = $parts[1] }
}

function Get-CertificateBlocks {
    param([Parameter(Mandatory = $true)][string] $Text)

    $regex = [regex]'(?s)-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----'
    @($regex.Matches($Text) | ForEach-Object { $_.Value })
}

function ConvertTo-SpkiPin {
    param(
        [Parameter(Mandatory = $true)][string] $CertificatePem,
        [Parameter(Mandatory = $true)][string] $TempDir
    )

    $certPath = Join-Path $TempDir "cert.pem"
    $pubPath = Join-Path $TempDir "pub.pem"
    $derPath = Join-Path $TempDir "pub.der"

    Set-Content -LiteralPath $certPath -Value $CertificatePem -NoNewline -Encoding ascii
    Invoke-OpenSslText @("x509", "-pubkey", "-noout", "-in", $certPath) | Set-Content -LiteralPath $pubPath -Encoding ascii
    Invoke-OpenSslText @("pkey", "-pubin", "-outform", "der", "-in", $pubPath, "-out", $derPath) | Out-Null

    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $digest = $sha.ComputeHash([System.IO.File]::ReadAllBytes($derPath))
    } finally {
        $sha.Dispose()
    }

    [Convert]::ToBase64String($digest)
}

function Get-CertificateSubject {
    param(
        [Parameter(Mandatory = $true)][string] $CertificatePem,
        [Parameter(Mandatory = $true)][string] $TempDir
    )

    $certPath = Join-Path $TempDir "subject.pem"
    Set-Content -LiteralPath $certPath -Value $CertificatePem -NoNewline -Encoding ascii
    $subject = (Invoke-OpenSslText @("x509", "-noout", "-subject", "-in", $certPath)) -join " "
    $subject -replace '^subject=', ''
}

Write-Output "// Generated by tools/capture_api_pins.ps1 on $((Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))"
Write-Output "// Paste into com.sysadmindoc.nimbus.data.api.ApiCertificatePins.hostPins"
Write-Output "val hostPins: Map<String, List<String>> = mapOf("

foreach ($endpoint in $Endpoints) {
    $parsed = Split-Endpoint $endpoint
    $hostName = $parsed.Host
    $port = $parsed.Port

    Write-Verbose "    // $hostName"

    $chainText = (Invoke-OpenSslText @("s_client", "-servername", $hostName, "-connect", "${hostName}:$port", "-showcerts") -PipeEmptyInput) -join "`n"
    $certs = Get-CertificateBlocks $chainText
    if ($certs.Count -eq 0) {
        throw "no TLS chain returned for ${hostName}:$port"
    }

    Write-Output "    `"$hostName`" to listOf("

    for ($i = 0; $i -lt $certs.Count; $i++) {
        $label = if ($i -eq 0) { "leaf" } else { "intermediate-$i" }
        $tempDir = Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid().ToString("N"))
        New-Item -ItemType Directory -Path $tempDir | Out-Null
        try {
            $pin = ConvertTo-SpkiPin -CertificatePem $certs[$i] -TempDir $tempDir
            $subject = Get-CertificateSubject -CertificatePem $certs[$i] -TempDir $tempDir
            Write-Output "        `"sha256/$pin`", // ${label}: $subject"
        } finally {
            Remove-Item -LiteralPath $tempDir -Recurse -Force
        }
    }

    Write-Output "    ),"
}

Write-Output ")"
