#!/usr/bin/env bash
# capture_api_pins.sh — generate SPKI SHA-256 pins for ZeusWatch's keyed endpoints.
#
# Writes a formatted Kotlin snippet to stdout that can be pasted into
# ApiCertificatePins.hostPins. Captures the full chain (leaf + every
# intermediate) so rotation doesn't brick the app.
#
# Requires: openssl (1.1+), awk, sed.
#
# Usage:
#   tools/capture_api_pins.sh
#   tools/capture_api_pins.sh api.openweathermap.org:443 api.pirateweather.net:443
#
# When run without args, it captures the default set of keyed hosts.
set -euo pipefail

DEFAULT_HOSTS=(
    "api.openweathermap.org:443"
    "api.pirateweather.net:443"
    "pro.openweathermap.org:443"
)

HOSTS=("${@:-${DEFAULT_HOSTS[@]}}")

if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl not found on PATH" >&2
    exit 1
fi

pin_host() {
    local endpoint="$1"
    local host="${endpoint%%:*}"
    local port="${endpoint##*:}"
    [[ "$host" == "$endpoint" ]] && port=443

    echo "    // ${host}" >&2
    local chain
    chain=$(openssl s_client -servername "$host" -connect "$host:$port" -showcerts </dev/null 2>/dev/null \
        | awk '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/')
    if [[ -z "$chain" ]]; then
        echo "error: no TLS chain returned for $host:$port" >&2
        return 1
    fi

    echo "    \"$host\" to listOf("
    echo "$chain" | awk '
        /-----BEGIN CERTIFICATE-----/ { in_cert=1; cert=$0 "\n"; next }
        /-----END CERTIFICATE-----/   { cert=cert $0 "\n"; print cert; in_cert=0; next }
        in_cert                        { cert=cert $0 "\n" }
    ' | while read -r _ || [[ -n "$cert" ]]; do
        : # awk emits full certs above; we consume per-cert below.
    done

    # Per-certificate SPKI SHA-256
    local cert_index=0
    while IFS= read -r -d '' cert; do
        local label="leaf"
        [[ $cert_index -ge 1 ]] && label="intermediate-$cert_index"
        local pin
        pin=$(echo "$cert" \
            | openssl x509 -pubkey -noout \
            | openssl pkey -pubin -outform der 2>/dev/null \
            | openssl dgst -sha256 -binary \
            | openssl enc -base64)
        local subject
        subject=$(echo "$cert" | openssl x509 -noout -subject 2>/dev/null | sed 's/^subject=//')
        echo "        \"sha256/${pin}\", // ${label}: ${subject}"
        cert_index=$((cert_index + 1))
    done < <(echo "$chain" | awk '
        /-----BEGIN CERTIFICATE-----/ { in_cert=1; cert=$0 "\n"; next }
        /-----END CERTIFICATE-----/   { cert=cert $0 "\n"; printf "%s\0", cert; in_cert=0; next }
        in_cert                        { cert=cert $0 "\n" }
    ')
    echo "    ),"
}

cat <<EOF
// Generated by tools/capture_api_pins.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
// Paste into com.sysadmindoc.nimbus.data.api.ApiCertificatePins.hostPins
val hostPins: Map<String, List<String>> = mapOf(
EOF

for host in "${HOSTS[@]}"; do
    pin_host "$host"
done

echo ")"
